"""Added new columns

Revision ID: 61b2ee54fa4e
Revises: 60c08bd88294
Create Date: 2025-03-30 11:03:00.362149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b2ee54fa4e'
down_revision = '60c08bd88294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applied_for', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposal', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('freelancer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bid_amount', sa.Float(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['freelancer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applied_for', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bid_amount')
        batch_op.drop_column('freelancer_id')
        batch_op.drop_column('proposal')

    # ### end Alembic commands ###
